### ISSUE TITLE
Ambilight + Hue + diyHue lights slow refresh rate // Entertainment crashes // No DTLS/UDP usage

### ISSUE THREAD

**Issue by Burn-In** [diyhue/hassio-addon#11]
I updated my whole setup to the latest versions of all components. In Entertainment mode with a TV the strip of 5 diyHue lights is only updated slowly. It takes about 5 seconds to blend to the next color/brightness value. Not in nearly sync, like before.
In the past, in such situations of sluggish behaviour, restart of all components did fix it. Not this time.

The Addon log shows updates every 100-150ms:
`2022-10-19 12:13:47,986 - werkzeug - INFO - 192.168.188.56 - - [19/Oct/2022 12:13:47] "PUT /api/d8e267884e5311edaa8eb827eb232bf2/lights/1/state HTTP/1.1" 200 -
2022-10-19 12:13:48,141 - werkzeug - INFO - 192.168.188.56 - - [19/Oct/2022 12:13:48] "PUT /api/d8e267884e5311edaa8eb827eb232bf2/lights/4/state HTTP/1.1" 200 -
2022-10-19 12:13:48,290 - werkzeug - INFO - 192.168.188.56 - - [19/Oct/2022 12:13:48] "PUT /api/d8e267884e5311edaa8eb827eb232bf2/lights/2/state HTTP/1.1" 200 -
2022-10-19 12:13:48,444 - werkzeug - INFO - 192.168.188.56 - - [19/Oct/2022 12:13:48] "PUT /api/d8e267884e5311edaa8eb827eb232bf2/lights/5/state HTTP/1.1" 200 -
2022-10-19 12:13:48,563 - werkzeug - INFO - 192.168.188.56 - - [19/Oct/2022 12:13:48] "PUT /api/d8e267884e5311edaa8eb827eb232bf2/lights/3/state HTTP/1.1" 200 -`

Means "200" an acknowledge from the light?

My setup:
Add-on version: 2.0.7
System: Home Assistant OS 9.2  (aarch64 / raspberrypi3-64)
Home Assistant Core: 2022.10.4
Home Assistant Supervisor: 2022.10.0
Lights: Gradient_TV_Strip_WS2812.ino from 9/9/22

Any ideas?

**Comment by Burn-In** [comment]
After resetting the TVs Hue setup, the bridge will still found but cannot connected anymore.

While pressing the button the log shows:
`[2022-10-20 07:39:38,813] ERROR in app: Exception on /api [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/restful.py", line 76, in post
    last_button_press = bridgeConfig["config"]["linkbutton"]["lastlinkbuttonpushed"]
TypeError: 'bool' object is not subscriptable`

**Comment by Burn-In** [comment]
After setting up any component newly, fresh addon, fresh *.ino on ESP, also the TV has been resetted. The lights will be still updated slowly in entertainment mode. Hue Essentials finds the bridge but then looses connection.

**Comment by mariusmotea** [comment]
But do you see in logs something related to entertainment mode? I think it is not using the entertainment mode since that cannot work slowly.

**Comment by Burn-In** [comment]
I guess the bridge receives Entertainment info from the TV (192.168.188.56):

2022-11-01 22:07:17,896 - flaskUI.restful - DEBUG - {'transitiontime': 8, 'xy': [0.22791263461112976, 0.2783275544643402]}
2022-11-01 22:07:17,949 - flaskUI.restful - DEBUG - [{'success': {'/lights/1/state/transitiontime': 8}}, {'success': {'/lights/1/state/xy': [0.22791263461112976, 0.2783275544643402]}}]
2022-11-01 22:07:17,955 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:17] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/1/state HTTP/1.1" 200 -
2022-11-01 22:07:18,010 - flaskUI.restful - DEBUG - {'transitiontime': 8, 'xy': [0.20215381681919098, 0.22303035855293274]}
2022-11-01 22:07:18,101 - flaskUI.restful - DEBUG - [{'success': {'/lights/5/state/transitiontime': 8}}, {'success': {'/lights/5/state/xy': [0.20215381681919098, 0.22303035855293274]}}]
2022-11-01 22:07:18,106 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:18] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/5/state HTTP/1.1" 200 -
2022-11-01 22:07:18,161 - flaskUI.restful - DEBUG - {'bri': 254, 'transitiontime': 8}
2022-11-01 22:07:18,266 - services.eventStreamer - DEBUG - {'creationtime': '2022-11-01T22:07:18Z', 'data': [{'id': '8e680816-203a-5bd6-a64c-b730bb400d23', 'id_v1': '/lights/5', 'identify': {}, 'metadata': {'archetype': 'hue_lightstrip', 'name': 'NodeMCU 5'}, 'product_data': {'certified': True, 'manufacturer_name': 'Signify Netherlands B.V.', 'product_archetype': 'hue_lightstrip', 'product_name': 'Hue lightstrip plus', 'software_version': '1.90.1', 'model_id': 'LST002'}, 'services': [{'rid': 'eeb103a0-5be2-4fc9-8b0e-3e7dfb0cb8c9', 'rtype': 'light'}, {'rid': '71048b00-c623-5877-8c98-dcd0db32bdfa', 'rtype': 'zigbee_connectivity'}, {'rid': '03dfa2e8-0d8a-5829-879a-5574478b7364', 'rtype': 'entertainment'}], 'type': 'device'}], 'id': 'e2ece4c6-20c7-4e60-b444-3c14b50cc986', 'type': 'update'}
2022-11-01 22:07:18,460 - flaskUI.restful - DEBUG - [{'success': {'/lights/2/state/bri': 254}}, {'success': {'/lights/2/state/transitiontime': 8}}]
2022-11-01 22:07:18,467 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:18] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/2/state HTTP/1.1" 200 -
2022-11-01 22:07:18,523 - flaskUI.restful - DEBUG - {'transitiontime': 8, 'xy': [0.2278694212436676, 0.24196171760559082]}
2022-11-01 22:07:18,583 - flaskUI.restful - DEBUG - [{'success': {'/lights/3/state/transitiontime': 8}}, {'success': {'/lights/3/state/xy': [0.2278694212436676, 0.24196171760559082]}}]
2022-11-01 22:07:18,587 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:18] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/3/state HTTP/1.1" 200 -
2022-11-01 22:07:18,643 - flaskUI.restful - DEBUG - {'bri': 254, 'transitiontime': 8}
2022-11-01 22:07:18,702 - flaskUI.restful - DEBUG - [{'success': {'/lights/4/state/bri': 254}}, {'success': {'/lights/4/state/transitiontime': 8}}]
2022-11-01 22:07:18,706 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:18] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/4/state HTTP/1.1" 200 -
2022-11-01 22:07:18,768 - services.eventStreamer - DEBUG - {'creationtime': '2022-11-01T22:07:18Z', 'data': [{'id': '8087696b-9618-51cd-9390-76597f05faf0', 'id_v1': '/lights/3', 'identify': {}, 'metadata': {'archetype': 'hue_lightstrip', 'name': 'NodeMCU 3'}, 'product_data': {'certified': True, 'manufacturer_name': 'Signify Netherlands B.V.', 'product_archetype': 'hue_lightstrip', 'product_name': 'Hue lightstrip plus', 'software_version': '1.90.1', 'model_id': 'LST002'}, 'services': [{'rid': '0ce6c2a6-47a2-49d3-96bc-747ef68f74f2', 'rtype': 'light'}, {'rid': '63022dcc-2fb9-5343-a336-0f9ed3a351b5', 'rtype': 'zigbee_connectivity'}, {'rid': 'deb34cbd-5cef-5211-bb92-cea4a423ad2f', 'rtype': 'entertainment'}], 'type': 'device'}], 'id': '70faff26-d308-43fb-a94c-dbb279d898d2', 'type': 'update'}
2022-11-01 22:07:18,769 - services.eventStreamer - DEBUG - {'creationtime': '2022-11-01T22:07:18Z', 'data': [{'id': '6cfd2e7c-d717-5211-bec7-76cd011e0c8a', 'id_v1': '/lights/4', 'identify': {}, 'metadata': {'archetype': 'hue_lightstrip', 'name': 'NodeMCU 4'}, 'product_data': {'certified': True, 'manufacturer_name': 'Signify Netherlands B.V.', 'product_archetype': 'hue_lightstrip', 'product_name': 'Hue lightstrip plus', 'software_version': '1.90.1', 'model_id': 'LST002'}, 'services': [{'rid': '27bc6977-fd41-4789-bfbd-38c68e70c999', 'rtype': 'light'}, {'rid': '999a37c0-3680-58fe-8b27-1d198b0235f7', 'rtype': 'zigbee_connectivity'}, {'rid': '3e9314fd-5726-53d8-8703-c501c82e137b', 'rtype': 'entertainment'}], 'type': 'device'}], 'id': 'b4ca3303-59ed-4be8-9d46-a56665e2705d', 'type': 'update'}
2022-11-01 22:07:18,982 - flaskUI.restful - DEBUG - {'bri': 254, 'transitiontime': 8}
2022-11-01 22:07:19,054 - flaskUI.restful - DEBUG - [{'success': {'/lights/1/state/bri': 254}}, {'success': {'/lights/1/state/transitiontime': 8}}]

I don't see any transmission to the lights. As per debug, the ESP light don't receive UDP packets, it stays in lightEngine mode.
But one strange observation: While Entertainment should be on, in the webinterface of the light, the brightness slider is moving back and forth.
Could it be that the light is updated via http not udp?

**Comment by mariusmotea** [comment]
What you paste here is not using the entertainment protocol (UDP based) but the regular Hue V1 API (http based).

> 2022-11-01 22:07:18,467 - werkzeug - INFO - 192.168.188.56 - - [01/Nov/2022 22:07:18] "PUT /api/243103aa5a2711ed9d1ab827eb232bf2/lights/2/state HTTP/1.1" 200 -
2022-11-01 22:07:18,523 - flaskUI.restful - DEBUG - {'transitiontime': 8, 'xy': [0.2278694212436676, 0.24196171760559082]}

**Comment by Burn-In** [comment]
That matches my assumptions. This dynamically xy values are also received over http by the ESP server while the TV sends entertainment data. No UDP data is transmitted.

09:00:54.416 -> lights[0]. x/y 0.40 / 0.30
09:00:54.934 -> lights[1]. x/y 0.25 / 0.24
09:00:55.027 -> lights[2]. x/y 0.41 / 0.32
09:00:55.448 -> lights[0]. x/y 0.25 / 0.25
09:00:56.055 -> lights[1]. x/y 0.22 / 0.23
09:00:57.133 -> lights[2]. x/y 0.43 / 0.33
09:00:58.214 -> lights[1]. x/y 0.69 / 0.31
09:00:58.354 -> lights[0]. x/y 0.60 / 0.31
09:00:58.634 -> lights[4]. x/y 0.43 / 0.39
09:00:58.774 -> lights[2]. x/y 0.23 / 0.26
09:00:58.915 -> lights[3]. x/y 0.43 / 0.43
09:00:59.008 -> lights[1]. x/y 0.46 / 0.49
09:00:59.103 -> lights[0]. x/y 0.43 / 0.45
09:00:59.907 -> lights[2]. x/y 0.23 / 0.26
09:01:00.048 -> lights[4]. x/y 0.40 / 0.38
09:01:00.141 -> lights[0]. x/y 0.41 / 0.43
09:01:00.282 -> lights[3]. x/y 0.39 / 0.39
09:01:01.031 -> lights[2]. x/y 0.22 / 0.24
09:01:01.453 -> lights[1]. x/y 0.46 / 0.48
09:01:01.923 -> lights[3]. x/y 0.42 / 0.41
09:01:02.157 -> lights[0]. x/y 0.40 / 0.42
09:01:02.250 -> lights[2]. x/y 0.29 / 0.31
09:01:03.424 -> lights[2]. x/y 0.26 / 0.28
09:01:03.565 -> lights[3]. x/y 0.41 / 0.41

That causes the slow response. Are there no UDP data coming from the TV?

**Comment by Burn-In** [comment]
Another suspicious thing is the appearence of the addon card:

![image](https://user-images.githubusercontent.com/33746005/199437795-7567b35d-b6a5-4e6d-ba4b-328cf06db511.png)

It looks like stopped but the log is running, the bridge frontend is reachable, bridge and lights can be found, data were send. Refreshing or HA restart don't fix it.

**Comment by mariusmotea** [comment]
When entertainment starts you will see logs with service.entertainment topic and a post in a group action state with body `{"active": true}`

**Comment by Burn-In** [comment]
Also when i start a Hue Essentials entertainment effect, only `services.eventStreamer` appears and the lights were also only updated via http.
Are the UDP packets already generated in the source (Hue Essentials or Ambilight+Hue-TV) and only forwarded by the bridge? If so, why are both sources sending entertainment only over http?
If not, how to force the bridge in entertainment mode?

**Comment by mariusmotea** [comment]
Be aware that there are non entertainment effects also. `services.eventStreamer` is not entertainment service, is something else. When entertainment is used DTLS protocol is used up to the bridge and from there UDP to ESP lights.

**Comment by Burn-In** [comment]
Got it. Now it looks different:

2022-11-02 22:32:25,326 - flaskUI.restful - DEBUG - {'stream': {'active': False}}
2022-11-02 22:32:25,326 - flaskUI.restful - INFO - stop hue entertainent
2022-11-02 22:32:25,349 - functions.rules - DEBUG - Processing rules for Entertainment-Bereich 1
2022-11-02 22:32:25,350 - flaskUI.restful - DEBUG - [{'success': {'/groups/1/stream': {'active': False}}}]
openssl: no process found
2022-11-02 22:32:25,360 - werkzeug - INFO - 192.168.188.62 - - [02/Nov/2022 22:32:25] "PUT /api/hueess165af411edba50b827eb232bf2/groups/1 HTTP/1.1" 200 -
2022-11-02 22:32:25,393 - werkzeug - INFO - 192.168.188.62 - - [02/Nov/2022 22:32:25] "GET /clip/v2/resource/entertainment HTTP/1.1" 200 -
2022-11-02 22:32:25,424 - werkzeug - INFO - 192.168.188.62 - - [02/Nov/2022 22:32:25] "GET /clip/v2/resource/entertainment_configuration HTTP/1.1" 200 -
2022-11-02 22:32:25,482 - services.eventStreamer - DEBUG - {'creationtime': '2022-11-02T22:32:25Z', 'data': [{'configuration_type': 'screen', 'locations': {'service_locations': [{'positions': [{'x': -0.8, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}, 'position': {'x': -0.8, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': -0.4, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '8f97d488-7273-521f-bdb9-f3f4b71ebb58', 'rtype': 'entertainment'}, 'position': {'x': -0.4, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.0, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '5efd605a-6c7f-597b-b360-977f2abb3ef3', 'rtype': 'entertainment'}, 'position': {'x': 0.0, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '2503659f-46d0-5271-95f8-ea6c90d063bf', 'rtype': 'entertainment'}, 'position': {'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.8, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '1eeca3de-066f-5f73-9590-38127166c786', 'rtype': 'entertainment'}, 'position': {'x': 0.8, 'y': -0.8, 'z': 0.0}}]}, 'metadata': {'name': 'Entertainment-Bereich 1'}, 'id_v1': '/groups/1', 'stream_proxy': {'mode': 'auto', 'node': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}}, 'light_services': [{'rtype': 'light', 'rid': 'ee4a0635-c3be-43f2-bc9c-7fa8d060bcd4'}, {'rtype': 'light', 'rid': '5790e74d-e0b6-46c2-8724-348dffc44de1'}, {'rtype': 'light', 'rid': '62eee84f-3483-4132-9c83-226f7372cafd'}, {'rtype': 'light', 'rid': '5d23af9a-be8e-4cfd-9b74-736df3d41cdc'}, {'rtype': 'light', 'rid': '95d59265-f7ec-4118-9a1c-8287def8fdc2'}], 'channels': [{'channel_id': 0, 'members': [{'index': 0, 'service': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}}], 'position': {'x': -0.8, 'y': -0.8, 'z': 0.0}}, {'channel_id': 1, 'members': [{'index': 0, 'service': {'rid': '8f97d488-7273-521f-bdb9-f3f4b71ebb58', 'rtype': 'entertainment'}}], 'position': {'x': -0.4, 'y': -0.8, 'z': 0.0}}, {'channel_id': 2, 'members': [{'index': 0, 'service': {'rid': '5efd605a-6c7f-597b-b360-977f2abb3ef3', 'rtype': 'entertainment'}}], 'position': {'x': 0.0, 'y': -0.8, 'z': 0.0}}, {'channel_id': 3, 'members': [{'index': 0, 'service': {'rid': '2503659f-46d0-5271-95f8-ea6c90d063bf', 'rtype': 'entertainment'}}], 'position': {'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}}, {'channel_id': 4, 'members': [{'index': 0, 'service': {'rid': '1eeca3de-066f-5f73-9590-38127166c786', 'rtype': 'entertainment'}}], 'position': {'x': 0.8, 'y': -0.8, 'z': 0.0}}], 'id': '75865421-fddb-5232-862d-7c8a8e0620e5', 'type': 'entertainment_configuration', 'name': 'Entertainment-Bereich 1', 'status': 'inactive'}], 'id': '4a735255-828d-48b6-9c39-c32281709d4a', 'type': 'update'}

**Comment by mariusmotea** [comment]
Ok, you get the error "openssl: no process found". How you installed diyhue?

**Comment by Burn-In** [comment]
Multiple times thru the Add-on store.

**Comment by Burn-In** [comment]
Is there anything that I can do? Check something?

**Comment by mariusmotea** [comment]
Sorry i read the logs in the wrong way. You paste here the logs that try to stop openssl not the ones that start it (must see `{'stream': {'active': True}}`). In this case openssl process not found means it was unable to start openssl so maybe you have another error there during the execution of openssl.

**Comment by Burn-In** [comment]
But this is what i get immediately after starting an entertainment effect. Also Hue essentials brings immediately an error and stopps entertainment.

2022-11-07 06:17:12,160 - werkzeug - INFO - 192.168.188.62 - - [07/Nov/2022 06:17:12] "PUT /api/hueess985b4311edba50b827eb232bf2/groups/1 HTTP/1.1" 200 -
openssl: no process found
2022-11-07 06:17:12,243 - werkzeug - INFO - 192.168.188.62 - - [07/Nov/2022 06:17:12] "GET /clip/v2/resource/entertainment HTTP/1.1" 200 -
2022-11-07 06:17:12,254 - services.eventStreamer - DEBUG - {'creationtime': '2022-11-07T06:17:12Z', 'data': [{'configuration_type': 'screen', 'locations': {'service_locations': [{'positions': [{'x': -0.8, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}, 'position': {'x': -0.8, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': -0.4, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '8f97d488-7273-521f-bdb9-f3f4b71ebb58', 'rtype': 'entertainment'}, 'position': {'x': -0.4, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.0, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '5efd605a-6c7f-597b-b360-977f2abb3ef3', 'rtype': 'entertainment'}, 'position': {'x': 0.0, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '2503659f-46d0-5271-95f8-ea6c90d063bf', 'rtype': 'entertainment'}, 'position': {'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}}, {'positions': [{'x': 0.8, 'y': -0.8, 'z': 0.0}], 'service': {'rid': '1eeca3de-066f-5f73-9590-38127166c786', 'rtype': 'entertainment'}, 'position': {'x': 0.8, 'y': -0.8, 'z': 0.0}}]}, 'metadata': {'name': 'Entertainment'}, 'id_v1': '/groups/1', 'stream_proxy': {'mode': 'auto', 'node': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}}, 'light_services': [{'rtype': 'light', 'rid': 'ee4a0635-c3be-43f2-bc9c-7fa8d060bcd4'}, {'rtype': 'light', 'rid': '5790e74d-e0b6-46c2-8724-348dffc44de1'}, {'rtype': 'light', 'rid': '62eee84f-3483-4132-9c83-226f7372cafd'}, {'rtype': 'light', 'rid': '5d23af9a-be8e-4cfd-9b74-736df3d41cdc'}, {'rtype': 'light', 'rid': '95d59265-f7ec-4118-9a1c-8287def8fdc2'}], 'channels': [{'channel_id': 0, 'members': [{'index': 0, 'service': {'rid': '1c9c36f0-8f44-5fe1-bb63-e5aa75aad471', 'rtype': 'entertainment'}}], 'position': {'x': -0.8, 'y': -0.8, 'z': 0.0}}, {'channel_id': 1, 'members': [{'index': 0, 'service': {'rid': '8f97d488-7273-521f-bdb9-f3f4b71ebb58', 'rtype': 'entertainment'}}], 'position': {'x': -0.4, 'y': -0.8, 'z': 0.0}}, {'channel_id': 2, 'members': [{'index': 0, 'service': {'rid': '5efd605a-6c7f-597b-b360-977f2abb3ef3', 'rtype': 'entertainment'}}], 'position': {'x': 0.0, 'y': -0.8, 'z': 0.0}}, {'channel_id': 3, 'members': [{'index': 0, 'service': {'rid': '2503659f-46d0-5271-95f8-ea6c90d063bf', 'rtype': 'entertainment'}}], 'position': {'x': 0.40000000000000013, 'y': -0.8, 'z': 0.0}}, {'channel_id': 4, 'members': [{'index': 0, 'service': {'rid': '1eeca3de-066f-5f73-9590-38127166c786', 'rtype': 'entertainment'}}], 'position': {'x': 0.8, 'y': -0.8, 'z': 0.0}}], 'id': '180bba57-0e8c-535d-aaf6-9bd19754e0a2', 'type': 'entertainment_configuration', 'name': 'Entertainment', 'status': 'inactive'}], 'id': '0d6d6193-172d-4d84-8890-0e4b80f624bd', 'type': 'update'}
2022-11-07 06:17:12,296 - werkzeug - INFO - 192.168.188.62 - - [07/Nov/2022 06:17:12] "GET /clip/v2/resource/entertainment_configuration HTTP/1.1" 200 -
2022-11-07 06:17:19,612 - werkzeug - INFO - 192.168.188.62 - - [07/Nov/2022 06:17:19] "GET /api/hueess985b4311edba50b827eb232bf2 HTTP/1.1" 200 -
2022-11-07 06:17:29,696 - werkzeug - INFO - 192.168.188.62 - - [07/Nov/2022 06:17:29] "GET /api/hueess985b4311edba50b827eb232bf2 HTTP/1.1" 200 -

**Comment by Burn-In** [comment]
I did again some investigations. Here my findings:
- To use the TVs Ambilight + Hue feature (my demand) it isn't needed to define an entertainment area. Areas are only used by the Apps.
- It is possible to pair every light detected by the bridge with the TV.
- It is not depending on the detected diyHue light type. It happens for LST002 strips and for LCT015 bulbs as well.
- The bridge receives dynamic Ambilight data for every light from the TV.
- Probably the data are not using DTLS, therefore the bridge don't start the UDP based EntertainmentStream but only the HTTP based EventStream. This causes the lag in the refresh rate.
- Still the questions: What pretends the TV to send over DTLS? Is the handshake disturbed?
- It works very well with the not anymore maintained /maxbec/hassio-diyHue Addon v1.5.0 together with diyHue lights based on older *.ino code. Until probably a HA update brokes it.

**Comment by Burn-In** [comment]
As per @Mevel this issue is related to the addons inability to use OpenSSL, in contrary to a container installation of diyHue. OpenSSL is quite not installed and running.
Is there a chance that this will be fixed in the future?

**Comment by Burn-In** [comment]
Issue has been solved by version 2.0.8

Thanks
