### ISSUE TITLE
Installation of add-on fails

### ISSUE THREAD

**Issue by apekatten** [diyhue/hassio-addon#17]
Installation of add-on fails with the following error
```
The command '/bin/bash -o pipefail -c curl -J -L -o $diyhue.tar.gz "https://github.com/diyhue/diyHue/archive/refs/heads/master.tar.gz" && tar xzvf $diyhue.tar.gz --strip-components=1 -C diyhue && rm -rf $diyhue.tar.gz && pip3 install -r /diyhue/requirements.txt --no-cache-dir' returned a non-zero code: 1
```

Cloning to desktop and trying to `docker build hassio-addon/diyhue` also fails the same way
```
7.503   Downloading PyYAML-6.0.tar.gz (124 kB)
7.665   Installing build dependencies: started
11.29   Installing build dependencies: finished with status 'done'
11.29   Getting requirements to build wheel: started
11.54   Getting requirements to build wheel: finished with status 'error'
11.54   ERROR: Command errored out with exit status 1:
11.54    command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpmytzzk7x
11.54        cwd: /tmp/pip-install-uebt051l/pyyaml
11.54   Complete output (48 lines):
11.54   running egg_info
11.54   writing lib/PyYAML.egg-info/PKG-INFO
11.54   writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
11.54   writing top-level names to lib/PyYAML.egg-info/top_level.txt
11.54   Traceback (most recent call last):
11.54     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
11.54       main()
11.54     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
11.54       json_out['return_val'] = hook(**hook_input['kwargs'])
11.54     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
11.54       return hook(config_settings)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
11.54       return self._get_build_requires(config_settings, requirements=['wheel'])
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
11.54       self.run_setup()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
11.54       exec(code, locals())
11.54     File "<string>", line 288, in <module>
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
11.54       return distutils.core.setup(**attrs)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
11.54       return run_commands(dist)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
11.54       dist.run_commands()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
11.54       self.run_command(cmd)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
11.54       super().run_command(command)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
11.54       cmd_obj.run()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 314, in run
11.54       self.find_sources()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
11.54       mm.run()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 551, in run
11.54       self.add_defaults()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
11.54       sdist.add_defaults(self)
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
11.54       super().add_defaults()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
11.54       self._add_defaults_ext()
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
11.54       self.filelist.extend(build_ext.get_source_files())
11.54     File "<string>", line 204, in get_source_files
11.54     File "/tmp/pip-build-env-deub1gv4/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
11.54       raise AttributeError(attr)
11.54   AttributeError: cython_sources
11.54   ----------------------------------------
11.54 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpmytzzk7x Check the logs for full command output.
11.72 WARNING: You are using pip version 20.2.4; however, version 23.2.1 is available.
11.72 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
Dockerfile:26
--------------------
  25 |     # Download diyhue and untar it
  26 | >>> RUN curl -J -L -o $diyhue.tar.gz "https://github.com/diyhue/diyHue/archive/refs/heads/master.tar.gz" \
  27 | >>>      && tar xzvf $diyhue.tar.gz --strip-components=1 -C diyhue \
  28 | >>>      && rm -rf $diyhue.tar.gz \
  29 | >>>      && pip3 install -r /diyhue/requirements.txt --no-cache-dir
  30 |
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c curl -J -L -o $diyhue.tar.gz \"https://github.com/diyhue/diyHue/archive/refs/heads/master.tar.gz\" \t&& tar xzvf $diyhue.tar.gz --strip-components=1 -C diyhue \t&& rm -rf $diyhue.tar.gz \t&& pip3 install -r /diyhue/requirements.txt --no-cache-dir" did not complete successfully: exit code: 1
```

**Comment by Joly0** [comment]
Got the same error

**Comment by mariusmotea** [comment]
Thanks for confirmation. I changed this also in the repository.

**Comment by apekatten** [comment]
Awesome! I can confirm that the installation worked for me now. Thank you for the quick replyt and resolution :)
