### ISSUE TITLE
Certificate issue in home assistant supervised diyhue addon

### ISSUE THREAD

**Issue by connor-peters** [diyhue/hassio-addon#42]
Hi together,
I experienced an issue after installing the addon. I noticed that I couldn't link the emulated bridge, neither in the HUE nor in the HUE Essentials app. Therefore I had a look into the addon's log and realized that there must be an issue regarding the certificate:

-----------------------------------------------------------
 Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.19
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.10.0
 Home Assistant Supervisor: 2024.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = aarch64
Serve HTTPS
2024-10-19 15:52:27,674 - configManager.argumentHandler - 122 - INFO - Using Host 192.168.2.161:80
2024-10-19 15:52:27,675 - configManager.argumentHandler - 142 - INFO - Host MAC given as d83add38483a
2024-10-19 15:52:27,676 - configManager.argumentHandler - 167 - INFO - IP range for light discovery: 0-255
2024-10-19 15:52:27,677 - configManager.argumentHandler - 176 - INFO - Deconz IP given as 127.0.0.1
2024-10-19 15:52:27,677 - configManager.argumentHandler - 183 - INFO - Online Discovery/Remote API Enabled!
2024-10-19 15:52:27,684 - configManager.argumentHandler - 122 - INFO - Using Host 192.168.2.161:80
2024-10-19 15:52:27,685 - configManager.argumentHandler - 142 - INFO - Host MAC given as d83add38483a
2024-10-19 15:52:27,686 - configManager.argumentHandler - 167 - INFO - IP range for light discovery: 0-255
2024-10-19 15:52:27,686 - configManager.argumentHandler - 176 - INFO - Deconz IP given as 127.0.0.1
2024-10-19 15:52:27,687 - configManager.argumentHandler - 183 - INFO - Online Discovery/Remote API Enabled!
2024-10-19 15:52:27,699 - configManager.argumentHandler - 29 - INFO - Debug logging disabled!
2024-10-19 15:52:27,754 - configManager.configHandler - 244 - INFO - Config loaded
2024-10-19 15:52:28,377 - services.updateManager - 30 - INFO - no swversion number update from Philips
2024-10-19 15:52:28,675 - services.updateManager - 56 - INFO - creation_time diyHue : 2024-10-19 13
2024-10-19 15:52:28,676 - services.updateManager - 57 - INFO - publish_time  diyHue : 2024-10-01 19
2024-10-19 15:52:28,916 - services.updateManager - 94 - INFO - creation_time UI : 2024-10-19 13
2024-10-19 15:52:28,917 - services.updateManager - 95 - INFO - publish_time  UI : 2024-09-02 18
2024-10-19 15:52:28,918 - services.updateManager - 66 - INFO - no update for diyHue or UI on github
2024-10-19 15:52:28,920 - services.remoteDiscover - 10 - INFO - Starting discovery service
2024-10-19 15:52:28,926 - services.stateFetch - 12 - INFO - start lights sync
2024-10-19 15:52:28,929 - services.ssdp - 39 - INFO - start ssdp broadcast
2024-10-19 15:52:28,929 - services.ssdp - 25 - INFO - starting ssdp...
2024-10-19 15:52:28,932 - services.mdns - 8 - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
2024-10-19 15:52:28,961 - werkzeug - 225 - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2024-10-19 15:52:28,963 - werkzeug - 225 - INFO -  * Running on http://192.168.2.161:80/ (Press CTRL+C to quit)
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/HueEmulator3.py", line 93, in runHttps
    ctx.load_cert_chain(certfile=CONFIG_PATH + "/cert.pem")
ssl.SSLError: [SSL] PEM lib (_ssl.c:4023)

I already tried to reinstall the addon, but so far without success. The output of "curl https://127.0.0.1/api/nouser -k -v" is the following:

*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 failed: Verbindungsaufbau abgelehnt
* Failed to connect to 127.0.0.1 port 443: Verbindungsaufbau abgelehnt
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 443: Verbindungsaufbau abgelehnt

Does anybody have an idea how to fix this? Thanks in advance!

**Comment by connor-peters** [comment]
I just found out that I directly started it the first time after installation, before adding mac address. Even uninstalling did not remove the falsely generated certificate. I removed it using ssh terminal, restarted the addon and it worked.
